### ISSUE TITLE
Import regex searches only for single quotes

### ISSUE THREAD

**Issue by StrahilKazlachev** [aurelia/tools#19]
The patterns for the import statements only matches if you've wrapped the path in single quotes
`import {process} from 'some/path/to/module'` and does not recognize the double quotes equivalent
`import {process} from "some/path/to/module"`. Is it because of the aurelia coding rules or because the regex gets too complicated to match the opening quote with the closing? If it is too much of a hassle to make it work with both double and single quotes, could you add somewhere a note about this quirk?

**Comment by EisenbergEffect** [comment]
This is something that really isn't supposed to be used outside our own build internal build process. It's very specific to how we are putting things together and it is based on our won code style rules. It also might go away in the future without warning...so I would be using this.

**Comment by StrahilKazlachev** [comment]
Ok, thanks. I wasn't sure whether it is appropriate or not to use it in the build of an aurelia plugin or not.
