### ISSUE TITLE
make no-console = 2

### ISSUE THREAD

**Issue by zewa666** [aurelia/tools#23]
dumb me I always manage to leave a trace of console.logs for simple debug scenarios when releasing a new version. Promoting the `no-console` eslint rule to 2 would greatly help as the gulp task highlights errors much better. I guess those few circumstances where console.xxx is really used can be explicitly allowed with inline comments

**Comment by EisenbergEffect** [comment]
Send a PR :)

**Comment by EisenbergEffect** [comment]
I'm going to close this for now.
