### ISSUE TITLE
Chrome extension - values of property getters?

### ISSUE THREAD

**Issue by blkbltjns** [aurelia/tools#33]
Looking at the contextual information for a bound DOM element, I can see member values but can't seem to see the values of property getters. Can you make these available?

**Comment by Alexander-Taran** [comment]
Issue moved to [aurelia/inspector #8](https://github.com/aurelia/inspector/issues/8) via [**ZenHub**](https://www.zenhub.com/)

**Comment by Alexander-Taran** [comment]
stale since 2016
copied to inspector
