### ISSUE TITLE
Chrome extension - context for repeated elements?

### ISSUE THREAD

**Issue by blkbltjns** [aurelia/tools#34]
Should I be able to see the datacontext for elements that are repeated inside a repeat.for? It looks like I can see the parent context but not the context for the repeated items.

**Comment by Alexander-Taran** [comment]
stale since 2016

**Comment by Alexander-Taran** [comment]
Issue moved to [aurelia/inspector #9](https://github.com/aurelia/inspector/issues/9) via [**ZenHub**](https://www.zenhub.com/)
