### ISSUE TITLE
relative path issue in  'sortFiles' function

### ISSUE THREAD

**Issue by hopkins700** [aurelia/tools#35]
Hi
I'm getting error when run 'build' task for the app like this:

src/subfolder/foo.js
src/subfolder/bar.js

bar.js contains the import statement as follows:
import {Foo} from './foo.js'

It seems there is an issue with 'sortFiles' function. Looks like it is looking for 'foo.js' file in 'src/foo.js' instead of 'src/subfolder/foo.js'

**Comment by EisenbergEffect** [comment]
That method is definitely not a general purpose tool. It's designed for use in specific repos we maintain. If you would like to fix it, please submit a PR, and we'll gladly merge. Otherwise, it's not going to be our top priority since it's not designed for anyone else to use but us.

**Comment by hopkins700** [comment]
Thanks, Rob. I just used aurelia environment as an example to build my own modules.. Anyway I made a pull request. Please, merge it with the main branch if you'll find it useful

**Comment by EisenbergEffect** [comment]
Fixed.
