### ISSUE TITLE
Chrome extension not working from within a Chrome extension

### ISSUE THREAD

**Issue by alexdresko** [aurelia/tools#40]
Some Inception-type stuff happening here. 

I have a Chrome extension that uses Aurelia, and I'm trying to get the Aurelia Chrome extension to help me create my own extension. However, the current Aurelia Chrome extension does not work if I inspect my own Chrome extension. 

Long story short, the current Aurelia extension initially fails because $0 is undefined in devtools.js. I got around that problem (let me know if you're interested), but quickly ran up against another. For whatever reason, even though my Chrome extension works, the Aurelia extension cannot find a .au property on any DOM element. 

Is there another way to retrieve the .au property and/or data? Does that make sense? 

I put a lot of time today into trying to figure this out and I feel like I'm close to making it work. Just have to go to sleep and I'm stuck.

**Comment by alexdresko** [comment]
The only way I can see this working is if it is if `page_getProperties` gets moved to a content script. 

Any thoughts on that? 

I don't want to ramble on for too long about this issue until someone else confirms my sanity or lack thereof.

**Comment by EisenbergEffect** [comment]
@sylvain-hamel Do you have any thoughts on this?

**Comment by sylvain-hamel** [comment]
No I don't. Sorry.

**Comment by EisenbergEffect** [comment]
@alexdresko Any further ideas on how we can improve things for your scenario?

**Comment by alexdresko** [comment]
@EisenbergEffect I haven't had anymore time to look at it, unfortunately. I sorta got disappointed after all the experimenting I tried to get it to work and temporarily gave up on the project I was working on. Also kinda _had_ to move on to another project. 

If you want to close this out, that's fine. I'll eventually get back to that Chrome plugin + TS + Aurelia project and may dig into this issue further at the time. I'll just come back to this issue when I get there. 

Thanks for following up. You're one of the best OSS project managers out there. You and @jerrynixon :)

**Comment by EisenbergEffect** [comment]
@alexdresko Thanks friend! I'll close this out for now. If at anytime you want to get working on tooling again, ping us and we'll help out however we can.
