### ISSUE TITLE
Build fails if imports use double-quotes

### ISSUE THREAD

**Issue by jsobell** [aurelia/tools#45]
Build task is hard-coded for single-quotes, and needs to allow double-quotes.

https://github.com/aurelia/tools/blob/master/src/build.js#L5-L7

Not sure if there are any possible implications re re-injecting them here:
https://github.com/aurelia/tools/blob/master/src/build.js#L91
Unlikely, although there could theoretically be a single-quote in an import name :) (yes, that would be really weird and unwise: `import * from "SamO'Neil"`)

**Comment by Alexander-Taran** [comment]
@jsobell is this still relevant?

**Comment by jsobell** [comment]
I think this was resolved a long time ago :)

**Comment by jsobell** [comment]
Sorry, closed by accident.
Well it looks like the code is still set for single-quotes only, so I'm guessing hasn't been resolved.
I'm not using this any longer, so haven't tested it.

**Comment by EisenbergEffect** [comment]
Closing this as won't fix since it a temporary internal tool that this is intended for.
