### ISSUE TITLE
Electron support

### ISSUE THREAD

**Issue by natrim** [aurelia/tools#46]
**I'm submitting a feature request**
- **Library Version:**
  Aurelia 1.0.0
  Arelia Context 1.2.0
- **Browser:**
  electron | chrome
- **Language:**
  TypeScript 2.2

**Current behavior:**
fails with error: chrome-api.js:124 responseCallback is not supported
(Seems like electron does not support callback on sendMessage)

**Expected/desired behavior:**
to work in electron

note: (redux devtools seems to have had same problem before this pull https://github.com/zalmoxisus/redux-devtools-extension/pull/158)

**Comment by EisenbergEffect** [comment]
I don't see what this has to do with Aurelia. There are a number of successfully Aurelia/Electron projects. Perhaps you have some other conflict or issue not related to Aurelia?

**Comment by natrim** [comment]
Aurelia works, this error is from Aurelia Context devtools, which don't work.
