### ISSUE TITLE
Does this chrome extension work with Aurelia RTM?

### ISSUE THREAD

**Issue by VagyokC4** [aurelia/tools#47]
**I'm submitting a bug report**
- **Library Version:**
  major.minor.patch-pre

**Please tell us about your environment:**
- **Operating System:**
  Windows [10]
- **Node Version:**
  5.1.0
  
  
- **NPM Version:**
  310.8
  
  
- **Browser:**
  Chrome 53.0.2785.143 m
- **Language:**
  ESNext

**Current behavior:**
I get the following values with a bound element I am looking at:
router-view.layoutModel:null
router-view.layoutView:null
router-view.layoutViewModel:null
router-view.swapOrder:null

**Expected/desired behavior:**
I'm expecting to see the actual bindings on the element (what I remember Aurelia Context doing with non rtm code).

- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
I don't think there were any chances that would have affected this. Have you tried it out with other elements besides the router-view?

**Comment by VagyokC4** [comment]
Yeah, I seem to only get this response regardless of which element I click on.

**Comment by plwalters** [comment]
Just checked it on the docs site and it appears to be working correctly the same way last time I remember.

**Comment by VagyokC4** [comment]
It should populate on any element with a bind attribute right?

**Comment by Alexander-Taran** [comment]
stale since 2016

**Comment by EisenbergEffect** [comment]
Closing since the new inspector works.
