### ISSUE TITLE
Link to extension not working

### ISSUE THREAD

**Issue by danny-bos-developer** [aurelia/tools#48]
**I'm submitting a bug report**
- **Library Version:**
  major.minor.patch-pre

**Please tell us about your environment:**
- **Operating System:**
  Windows 10
- **Node Version:**
  6.2.0
- **NPM Version:**
  3.8.9
- **Browser:**
  Chrome XX
- **Language:**
  ESNext

**Current behavior:**
I like to try the chrome plug-in aurelia-context using the link on the page:
http://blog.aurelia.io/2016/04/21/aurelia-cli-debug-tools-and-microsoft-collaboration/
When I click the "Give it a try" link, I get a 404 stating:
The requested URL was not found on this server. That’s all we know.

**Expected/desired behavior:**
A working link to the context extension.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

**Comment by EisenbergEffect** [comment]
I think it's a google apps account issue. We will look into it.

**Comment by michallepicki** [comment]
any progress on this?

**Comment by Alexander-Taran** [comment]
Moved on to inspector

Should be closed
