### ISSUE TITLE
protractor plugin: waitForRouterComplete() race condition

### ISSUE THREAD

**Issue by dmoebius** [aurelia/tools#50]
**I'm submitting a bug report**

* **Library Version:**
0.2.4

**Please tell us about your environment:**
* **Operating System:**
Linux (Arch 64bit)

* **Node Version:**
6.9.1

* **NPM Version:**
3.10.9

* **Browser:**
Chrome 54

* **Language:**
TypeScript 2.0.7

**Current behavior:**
The [Aurelia Navigation Skeletons](https://github.com/aurelia/skeleton-navigation) have the following function in `test/e2e/skeleton.po.[js/ts]`:
```js
  navigateTo(href) {
    element(by.css('a[href="' + href + '"]')).click();
    return browser.waitForRouterComplete();
  }
```
In the first line the anchor gets clicked. The second line causes the webdriver to wait for the next route change, then continue. This usually works if the browser is slow. If the browser is fast, the following happens:
1. the anchor gets clicked
2. the aurelia router changes state
3. `browser.waitForRouterComplete()` is called.

Since the route change already happened, this last method waits forever. That's a race condition.

**Expected/desired behavior:**

* **What is the expected behavior?**
I don't know how to clean this up. Ideally, `waitForRouterComplete()` should first add the routing event listener, then execute the business logic (e.g. clicking the anchor), and then wait for the event callback to be called. This means that `waitForRouterComplete()` should receive a callback (or something like that). 

* **What is the motivation / use case for changing the behavior?**
Sometimes failing e2e tests.

PS: I don't know where this issue belongs: either to **aurelia-tools**, or **[protractor-plugin](https://github.com/aurelia/protractor-plugin)** (which seems to be new), or even **[aurelia-skeleton-navigation](https://github.com/aurelia/skeleton-navigation)**.

**Comment by niieani** [comment]
The issue should be in protract-plugin as we're moving out that to its own separate repo and the plugin will soon be removed from aurelia-tools.
Thanks for bringing this up!

**Comment by niieani** [comment]
Issue moved to [aurelia/protractor-plugin #2](https://github.com/aurelia/protractor-plugin/issues/2) via [**ZenHub**](https://www.zenhub.com/)
