### ISSUE TITLE
Typescript config

### ISSUE THREAD

**Issue by jods4** [aurelia/tools#52]
I am very happy to see new Aurelia packages move towards a simple NPM based build, and Typescript the language of choice! Hopefully existing packages will slowly migrate.

That said I have a few comments on the `tsconfig.json`.

I see you use most strict options for maximum safety but you might have missed some:
- `noImplicitThis`, which is quite helpful at detecting non-obvious errors.
- `noFallthroughCasesInSwitch`

I also suggest the following relaxation: `suppressImplicitAnyIndexErrors`.
It avoids ugly code such as this example (found in `aurelia-webpack-loader`):
```ts
(PLATFORM as any).Loader = WebpackLoader;
```
By allowing dynamic access:
```ts
PLATFORM['Loader'] = WebpackLoader;
```
Of course you should properly type everything, but I find that it's nice to have an escape hatch for those occasions when you need one.

A big problem with the current TS build is that it emits its helpers at the top of each and every file (when they're used of course).
This is large, see `aurelia-webpack-loader` again for example:
```ts
"use strict";
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : new P(function (resolve) { resolve(result.value); }).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments)).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t;
    return { next: verb(0), "throw": verb(1), "return": verb(2) };
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = y[op[0] & 2 ? "return" : op[0] ? "throw" : "next"]) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [0, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
```
Aurelia is very modular, having those helpers repeated again and again would contribute a large bloat.
I suggest that you use the new option `importHelpers`. It does pretty much what it says:
```ts
import { __extends, __awaiter, __generator } from 'tslib';
```
And `tslib` becomes an additional dependency of Aurelia. 
That way the helpers are only included once in the final build, and even shared with my own TS code! 🙂
That works at least fine when you use NPM as your package manager, not sure about others (Bower?).

**Comment by niieani** [comment]
Hi jods4.

I'm aware of all these issues and have experimented with including `tslib`, but decided we want to wait until more of the Aurelia packages are using the new build system before we add a new external dependency. We'll switch probably very soon though. Also, we'll need to see how this behaves with non-NPM package managers before we flip the switch.

Regarding:
```
(PLATFORM as any).Loader = WebpackLoader;
```

I believe this is much better than dynamic access, because it signifies a problem with the typings that needs to be tackled. (By the way, I've already added the missing `Loader` property to the `PLATFORM`  interface, so this cast isn't needed anymore.)

Using dynamic access might also be slower in runtime, depending on the optimizations a given JS engine does.

`noImplicitThis` is definitely something we want to add to the default config.

**Comment by jods4** [comment]
> Also, we'll need to see how this behaves with non-NPM package managers before we flip the switch.

I did a quick search and apparently the package is also published on Bower. I guess that covers the main PMs (as Yarn uses npm repo and so do JSPM).

> Using dynamic access might also be slower in runtime, depending on the optimizations a given JS engine does.

AFAIK runtimes see a constant string access `x['a']` as _exactly equivalent_ to `x.a`. There is no semantic difference, only at the parser level. (Dynamic access with a non-constant string is different, of course.)

**Comment by EisenbergEffect** [comment]
@jdanyow Can you provide some feedback here?

**Comment by jods4** [comment]
Regarding the TS helpers, MS said they are considering making the imported name configurable. So instead of introducing a dep. on `tslib` in the future it might be possible to depend on an aurelia package if you prefer.

**Comment by EisenbergEffect** [comment]
That would definitely be my preference. I wondered if we could build them into the PAL somehow. But it could be a module as well. I just feel weird having a TS dep.

**Comment by jods4** [comment]
For the record:
MS shipped TS 2.2 without an option to configure which module contains the helpers.
It's still in discussion in Microsoft/Typescript#12502.

**Comment by Alexander-Taran** [comment]
something merged..
might be closed

**Comment by EisenbergEffect** [comment]
Closing since we've got some work ongoing for vNext that will address all this.
