### ISSUE TITLE
au new fails to install modules with npm install due to version conflict with babel-eslint

### ISSUE THREAD

**Issue by jadrake75** [aurelia/tools#65]
**I'm submitting a bug report**

* **Library Version:**
* aurelia-tools:2.0.0
* aurelia-cli:2.0.3

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
v14.18.3

* **NPM Version:**
8.3.0

* **Browser:**
all

* **Language:**
ESNext

**Current behavior:**
When running a "au new" and selecting any of the projects with ESNext if you do the "npm install" it will fail with the following error

````
√ Would you like to install all the npm dependencies? · Yes, use NPM
Installing project dependencies...

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vendor-2@0.1.0
npm ERR! Found: babel-eslint@10.1.0
npm ERR! node_modules/babel-eslint
npm ERR!   dev babel-eslint@"^10.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer babel-eslint@"^7.2.3" from aurelia-tools@2.0.0
npm ERR! node_modules/aurelia-tools
npm ERR!   dev aurelia-tools@"^2.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\jadra\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jadra\AppData\Local\npm-cache\_logs\2022-01-14T22_52_33_582Z-debug-0.log
Project dependencies were installed.
````

If you run the npm install with the "--force" flag it will work around this.  The version of babel-eslint needs to be resolved in the package.json for this module as it is too restrictive with other dependencies.

**Expected/desired behavior:**
npm install should never fail

**Comment by 3cp** [comment]
aurelia-tools has been removed from skeleton long ago. I just checked again, new project does not install aurelia-tools anymore.

Are you sure you are using latest aurelia-cli v2.0.3?

```
huocp@Chunpengs-MacBook-Pro ~/p/my-app> npm ls aurelia-tools
my-app@0.1.0 /Users/huocp/playground/my-app
└── (empty)

huocp@Chunpengs-MacBook-Pro ~/p/my-app [1]> npm ls aurelia-cli
my-app@0.1.0 /Users/huocp/playground/my-app
└── aurelia-cli@2.0.3 
```

**Comment by jadrake75** [comment]
ah ha.... you are right.  I have cli 2.0.3 in my projects but have only version v1.1.0 installed globally.

My mistake!

Verified updating the global instance to v2.0.3 does not show the issue.
