### ISSUE TITLE
Discover Binding Context

### ISSUE THREAD

**Issue by EisenbergEffect** [aurelia/tools#8]
It would be nice to have the ability to discover the binding context for any html element.

**Comment by AStoker** [comment]
This enhancement has been closed, but I've failed to find how to use this. Has it been implemented yet? If so, how would I be able to use it?

**Comment by EisenbergEffect** [comment]
It's been possible for a while now but the API is not easy to use and is subject to change. We will be adding a "friendlier" api for it soon. It doesn't have anything to do with the tools library though. This is a core capability of the templating engine.

**Comment by AStoker** [comment]
Gotcha, thanks.
