### ISSUE TITLE
when using sub folders, the in browser debug experience is broken.

### ISSUE THREAD

**Issue by paulvanbladel** [aurelia/tools#9]
So, let's focus on the navigation app sample and move both the flickr html/js in an sub folder /flickr and update the router accordingly.
After a build watch, the app still works, but the ES6 file (for flickr) is not included in the src folder.

So, when we open the app, things are as expected, the flickr files are not loaded, since systemjs will only load it when needed (great !)
![image](https://cloud.githubusercontent.com/assets/4886272/8324623/ad4845b2-1a52-11e5-8be8-ad4c86bea2e6.png)

Now, when we route to flickr, things change:
![image](https://cloud.githubusercontent.com/assets/4886272/8324642/d19508a6-1a52-11e5-9791-682c0acb9ba7.png)

The folder structure inside dist is a bit strange. There is folder created called src/flickr but the file is empty.
But the most annoying is that the original ES6 file for flickr is not under /src.

Thanks for helping.

**Comment by paulvanbladel** [comment]
Ok, I think I found a solution.
Inside the gulp build-system task update the sourcemaps.write line as follows:

.pipe(sourcemaps.write({includeContent: false, sourceRoot: '/src'}))

So, the sourceRoot should be an ABSOLUTE path (starting with /).

Inside paths.js the sourceRoot param is called sourceMapRelativePath. Don't understand this naming, because it's not really about a relative path?

Any side - effects ?

thanks
paul.

**Comment by EisenbergEffect** [comment]
We've fixed up our source maps support in the next release.
